### PR TITLE
PR's go to forked repo if its a forked repo

### LINKED ISSUE #372: Update Manager creates PR's on master repo, not the forked repo.
**Describe the bug**
Running the update manager on the forked repo, creates an PR on the master repository rather than on the forked repo. 

Example - https://github.com/saisankargochhayat/clai
Created a PR on - https://github.com/AICoE/clai/pull/1

Seems to be dependent on - https://github.com/packit-service/ogr/issues/307

### PR DESCRIPTION
**Pull request by saisankargochhayat**
## Related Issues and Dependencies
Should close https://github.com/thoth-station/kebechet/issues/372

### CODE REVIEW

**Review by KPostOffice — COMMENTED** [review]
```
    def create_pr(
        self,
        title: str,
        body: str,
        target_branch: str,
        source_branch: str,
        fork_username: str = None,
    ) -> PullRequest:
```
It doesn't look like `fork_username` will be set to `self.namespace` to me

**Comment by saisankargochhayat** [comment]
> ```
>     def create_pr(
>         self,
>         title: str,
>         body: str,
>         target_branch: str,
>         source_branch: str,
>         fork_username: str = None,
>     ) -> PullRequest:
> ```
> 
> It doesn't look like `fork_username` will be set to `self.namespace` to me

The username here refers to the namespace, that is the github-user/ org
for example - https://github.com/saisankargochhayat/srcops-testing/pull/3
Related PR - https://github.com/packit-service/ogr/pull/404

**Comment by KPostOffice** [comment]
I miscounted the number of arguments LGTM :+1:

**Review by KPostOffice — APPROVED** [review]
LGTM

**Pull request merged**
